### PR TITLE
Fix parallelization

### PR DESCRIPTION
**Pull request by mjc**
Previously, hashing only occurred on one thread.  Additionally, the access patterns were near-worst-case sometimes.

Additionally, the code was (and still is) way more complicated than necessary.

I haven't verified if the ignore code is right, but it looks to be.  Please review.

Please test on a single non-SSD, non-ZFS disk before merging.
Testing cold caches is difficult on this machine.

This PR is complete when:
- [x] BufReader to improve buffering
- [x] parallelizing with automatic num_cpus actually uses all cores
- [x] progress bar replaced with `indicatif` as it supports `Send`
- [x] sort files by inode before reading to improve spinning-rust performance (inode order is a bit of an approximation of file creation order)
- [x] option parsing works

Some smaller gains to be had on spinning rust if desired:
- `fiemap` with inode sort fallback (I don't have a filesystem that supports `fiemap `handy)
- Batched `posix_fadvise` (`POSIX_FADV_SEQUENTIAL`, `POSIX_FADV_WILLNEED`, with `POSIX_FADV_DONTNEED` afterward) calls to indicate that the OS should warm the caches before access.  
- `MAP_POPULATE` for mmap - not sure if this is faster on spinning rust

There is an option parsing bug where `--jobs` does not work. I'd rather just replace the whole option parsing with the newer style of clap, than try to fix that bug.

---

# Benchmarks
## System
- Ryzen 7 2700X
- 64GB 3200MT memory
- Samsung 970 EVO 1TB
- 9-disk SAS ZFS array in RAIDZ2 configuration

## Dataset
3,045 files, 40GB total.  ZFS compression disabled.
Size distribution:
```
  4k:      2
 16k:      6
 64k:      4
128k:     11
256k:     99
512k:     46
  1M:    176
  2M:     94
  4M:     84
  8M:   1280
 16M:    840
 32M:    382
 64M:     21
```

These are after the third run, to make sure the disk cache is warm.
The disk cache on this machine uses about 30GB of RAM.

### Warm cache
- SSD Before: 46 seconds, about 870MB/s because most of the data is in RAM.
```
quickdash -a sha1 --force --create ~/uncompressed/unpacked  22.68s user 22.42s system 96% cpu 46.566 total
```
- SSD After: 10.2 seconds, about 3.9GB/s because most of the data is cached.
```
cargo run --release -- -a sha1 --force --create ~/uncompressed/unpacked  25.16s user 38.71s system 626% cpu 10.189 total
```
- HDD Array Before: 4m50s, or about 138MB/s.  Slightly more than 50% of one disk's read performance, even with a warm cache.
```
quickdash -a sha1 --force --create ~/spinning-uncompressed/unpacked  31.07s user 30.77s system 21% cpu 4:49.98 total
```
- HDD Array After: 23 seconds, about 1.74GB/s which is pretty close to the 2250GB/s these disks are capable of on sequential reads.
```
cargo run --release -- -a sha1 --force --create   33.93s user 35.05s system 300% cpu 22.965 total
```

### Cold cache
- SSD Before: 50 seconds, about 800MB/s. 
```
quickdash -a sha1 --force --create ~/uncompressed/unpacked  22.92s user 23.79s system 93% cpu 49.831 total
```
- SSD After: 14 seconds, or about 2.86GB/s.  SSD is rated for 3500MB/s sequential.
```
cargo run --release -- -a sha1 --force --create ~/uncompressed/unpacked  24.99s user 34.71s system 422% cpu 14.144 total
```
- HDD Array Before: 6:13.54, or about 106MB/s
```
quickdash -a sha1 --force --create ~/spinning-uncompressed/unpacked  37.68s user 48.41s system 23% cpu 6:13.54 total
```
- HDD Array After: 1 minute 38 seconds, or about 408MB/s.  There's still a lot of room to improve since each disk was only getting about 60MB/s, and I suspect a single drive would have similar improvements left.
```
cargo run --release -- -a sha1 --force --create   38.40s user 44.48s system 84% cpu 1:38.27 total
```

### CODE REVIEW

**Comment by iamtakingithard** [comment]
Hello, @mjc!
Thanks for bringing improvements to my first command line Rust program I made, haha.

>There is an option parsing bug where --jobs does not work. I'd rather just replace the whole option parsing with the newer style of clap, than try to fix that bug.

Sure, use as you see fit. But yeah I do see it would be better just to upgrade clap to their v3 version.


>Please test on a single non-SSD, non-ZFS disk before merging.
Testing cold caches is difficult on this machine.

Sure, I will do testing with your PR just tell me what to use for benchmarking and I will do that.

**Comment by mjc** [comment]
I figured it was something like that! I'm learning that it's pretty easy to tell when someone is new, even if they're seasoned in other languages. Funnily enough I got the improvements originally from revisiting the first Rust program I made. I learned a bunch from reading this one too, though. I hadn't tried to do anything generic the way you did with your hash selection, I used traits for it instead.

I'd used this app a couple dozen times before and forgot about it, then went back after realizing mine is almost a superset if this.  I needed mine to work on 15TB of data, so it made sense to spend some time improving it this month. I basically managed to update yours with the same work I did for mine, in about 20 minutes 🙂

On Linux, the easiest way to test with any filesystem other than ZFS is to generate several thousand incompressible files that total in size to more RAM than you have memory, then:
`sync; echo 3 > /proc/sys/vm/drop_caches` before every run.  

I can whip up a quick script if you'd prefer, since I may have a bunch more changes for this PR.

I'm concerned (for both my app and yours tbh) that I may accidentally make things slower for single HDDs. I don't currently have a spare one handy.

**Comment by iamtakingithard** [comment]
>On Linux, the easiest way to test with any filesystem other than ZFS is to generate several thousand incompressible files that total in size to more RAM than you have memory, then:
sync; echo 3 > /proc/sys/vm/drop_caches before every run.

Okie, I will use that. And for script, sure why not.

>I'm concerned (for both my app and yours tbh) that I may accidentally make things slower for single HDDs. I don't currently have a spare one handy.

I fortunately do have a spare one.

Tbh, the only thing I don't really like in my software is how it check the hash sums. It uses regex for that, which it sucks but at the time I didn't have any other solution for that.

**Comment by iamtakingithard** [comment]
PR works, all good.

**Comment by iamtakingithard** [comment]
https://github.com/AndreVuillemot/QuickDash/pull/28/commits/468fcba9fa4cee09ae95802a62941de784e70c56

In this commit `SPINNER_STRINGS` should be replaced with just some text. Because Windows CMD terminal don't support showing Unicode emojis. I would instead used just some text. We can use this spinner below.

```['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏']```

**Comment by mjc** [comment]
The command line isn't the same with clap 3, currently.  I don't have time to make it identical.  It did massively simplify things, though.

**Comment by iamtakingithard** [comment]
> The command line isn't the same with clap 3, currently. I don't have time to make it identical. It did massively simplify things, though.

Yeah, clap v2 to clap v3 was the biggest pain for me to upgrade.

**Review by iamtakingithard — APPROVED** [review]

**Comment by iamtakingithard** [comment]
In general everything looks good.
I will test the PR, soon. PR will be still open since on your TODO, you still have some things to do.

**Comment by AndreVuillemot** [comment]
Also, do you want me to add you as crate authors and collaborator?

**Comment by mjc** [comment]
I don't think I have time to finish the fiemap, fadvise, etc stuff yet.

fiemap in particular is going to require me to find my mini-itx machine buried in a pile of extra hardware 🤣 since ZFS does not support it.

for fadvise there is [reapfrog](https://github.com/the8472/reapfrog). It works but you have to use `for-in` which I really don't like.  A replacement for it is on my to-do list.

Might be good to make these into issues, and I can revisit them when I get around to it, or maybe others will see it and contribute.

I'd be happy to be on the contributor list.  I don't know how much time I'll have to work on it in the future, though.  Happy to respond if you find a bug in my contributions.

BTW, I have some code in [my project](https://github.com/mjc/mame_coalesce) I cribbed these improvements from, for hashing files that are inside zip and 7z archives.  Could be a neat addition if you're interested, and you're welcome to take it, or add an issue for others to work on it.

**Comment by iamtakingithard** [comment]
Can you please add a list of available hashes? Also, it would be nice if you updated DOCS.md, with some of example usage with merged PR.

**Comment by mjc** [comment]
I updated `DOCS.md` with the literal output from the help.
However I'm realizing that the subcommand help is a little confusing, as it doesn't show that you should put general options before the subcommand, like:
```
-a xxh3 create --force ~/uncompressed/unpacked
```

I'll look into that in a couple hours.

**Comment by iamtakingithard** [comment]
All, good? Can I merge the PR now?

**Comment by mjc** [comment]
Yeah, it looks ready to me. I am working on a solution for the weird subcommand help message - I think I will need to submit an issue to clap for it.

**Pull request merged**
